version: '3.1'
services:
  app:
    image: bank-api
    container_name: bank-api
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres:12.10
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_bank_api

