version: '3.1'
services:
  app:
    image: bank-api
    container_name: bank-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    depends_on:
      - psqldb
  psqldb:
    image: postgres:12.10
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank_api
  flyway:
    image: flyway/flyway
    environment:
      - FLYWAY_EDITION=community
    command: -url=jdbc:postgresql://psqldb:5432/bank_api -schemas=migrations -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - $PWD/sql_versions:/flyway/sql
    depends_on:
      - psqldb