create table tb_bank (number varchar(3) not null, name varchar(60) not null, primary key (number));
create table tb_bank_account (id uuid not null, account varchar(8) not null, account_type int4 not null, agency varchar(4) not null, bank_number varchar(3) not null, tb_bank_holder_id uuid, primary key (id));
create table tb_bank_holder (id uuid not null, first_name varchar(20) not null, second_name varchar(40) not null, primary key (id));
create table tb_account_type (id int4 not null, name varchar(9) not null);
alter table tb_bank_account add constraint UK_461lcub13drjv0h41m1atavol unique (account);
alter table tb_bank_account add constraint FKq2apc02l3by1vh996f4udmb4j foreign key (tb_bank_holder_id) references tb_bank_holder;
create table tb_bank (number varchar(3) not null, name varchar(60) not null, primary key (number));
create table tb_bank_account (id uuid not null, account varchar(8) not null, account_type int4 not null, agency varchar(4) not null, bank_number varchar(3) not null, tb_bank_holder_id uuid, primary key (id));
create table tb_bank_holder (id uuid not null, first_name varchar(20) not null, second_name varchar(40) not null, primary key (id));
alter table tb_bank_account add constraint UK_461lcub13drjv0h41m1atavol unique (account);
alter table tb_bank_account add constraint FKq2apc02l3by1vh996f4udmb4j foreign key (tb_bank_holder_id) references tb_bank_holder;
create table tb_bank (number varchar(3) not null, name varchar(60) not null, primary key (number));
create table tb_bank_account (id uuid not null, account varchar(8) not null, account_type int4 not null, agency varchar(4) not null, bank_number varchar(3) not null, tb_bank_holder_id uuid, primary key (id));
create table tb_bank_holder (id uuid not null, first_name varchar(20) not null, second_name varchar(40) not null, primary key (id));
alter table tb_bank_account add constraint UK_461lcub13drjv0h41m1atavol unique (account);
alter table tb_bank_account add constraint FKq2apc02l3by1vh996f4udmb4j foreign key (tb_bank_holder_id) references tb_bank_holder;
create table tb_bank (number varchar(3) not null, name varchar(60) not null, primary key (number));
create table tb_bank_account (id uuid not null, account varchar(8) not null, account_type int4 not null, agency varchar(4) not null, bank_number varchar(3) not null, tb_bank_holder_id uuid, primary key (id));
create table tb_bank_holder (id uuid not null, first_name varchar(20) not null, second_name varchar(40) not null, primary key (id));
alter table tb_bank_account add constraint UK_461lcub13drjv0h41m1atavol unique (account);
alter table tb_bank_account add constraint FKq2apc02l3by1vh996f4udmb4j foreign key (tb_bank_holder_id) references tb_bank_holder;
create table tb_account_type(id integer NOT NULL,name varchar(9) NOT NULL);
INSERT INTO tb_account_type (id, name) values (0, 'CHECKINGS');
INSERT INTO tb_account_type (id, name) values (1, 'SAVINGS');